./.externalToolBuilders/.svn
./.settings/.svn
./bin/.svn
./bin/biz/.svn
./bin/biz/navius/.svn
./bin/biz/navius/saltroad/.svn
./bin/biz/navius/saltroad/constants/.svn
./bin/biz/navius/saltroad/kml/.svn
./bin/biz/navius/saltroad/kml/constants/.svn
./bin/biz/navius/saltroad/kml/XMLparser/.svn
./bin/biz/navius/saltroad/overlays/.svn
./bin/biz/navius/saltroad/trackwriter/.svn
./bin/biz/navius/saltroad/utils/.svn
./bin/org/.svn
./bin/org/andnav/.svn
./bin/org/andnav/osm/.svn
./bin/org/andnav/osm/contributor/.svn
./bin/org/andnav/osm/contributor/util/.svn
./bin/org/andnav/osm/exceptions/.svn
./bin/org/andnav/osm/util/.svn
./bin/org/andnav/osm/util/constants/.svn
./bin/org/andnav/osm/views/.svn
./bin/org/andnav/osm/views/controller/.svn
./bin/org/andnav/osm/views/overlay/.svn
./bin/org/andnav/osm/views/util/.svn
./bin/org/andnav/osm/views/util/constants/.svn
./bin/org/openintents/.svn
./bin/org/openintents/filemanager/.svn
./bin/org/openintents/filemanager/util/.svn
./ext/.svn
./ext/doc/.svn
./ext/img/.svn
./lib/.svn
./res/.svn
./res/drawable/.svn
./res/drawable-hdpi/.svn
./res/drawable-nodpi/.svn
./res/layout/.svn
./res/menu/.svn
./res/raw/.svn
./res/values/.svn
./res/values-es/.svn
./res/values-ru/.svn
./res/values-zh-rCN/.svn
./res/values-zh-rTW/.svn
./res/xml/.svn
./src/biz/.svn
./src/biz/navius/.svn
./src/biz/navius/saltroad/.svn
./src/biz/navius/saltroad/constants/.svn
./src/biz/navius/saltroad/kml/.svn
./src/biz/navius/saltroad/kml/constants/.svn
./src/biz/navius/saltroad/kml/XMLparser/.svn
./src/biz/navius/saltroad/overlays/.svn
./src/biz/navius/saltroad/trackwriter/.svn
./src/biz/navius/saltroad/utils/.svn
./src/org/.svn
./src/org/andnav/.svn
./src/org/andnav/osm/.svn
./src/org/andnav/osm/contributor/.svn
./src/org/andnav/osm/contributor/util/.svn
./src/org/andnav/osm/exceptions/.svn
./src/org/andnav/osm/util/.svn
./src/org/andnav/osm/util/constants/.svn
./src/org/andnav/osm/views/.svn
./src/org/andnav/osm/views/controller/.svn
./src/org/andnav/osm/views/overlay/.svn
./src/org/andnav/osm/views/util/.svn
./src/org/andnav/osm/views/util/constants/.svn
./src/org/openintents/.svn
./src/org/openintents/filemanager/.svn
./src/org/openintents/filemanager/util/.svn
